#-------------------
# TESTES LOCAIS
#====================

### POST /sobreviventes
POST http://localhost:5555/sobreviventes
Content-Type: application/json

{
   "resource": "/sobreviventes",
   "path": "/sobreviventes",
   "httpMethod": "POST",
   "body": "{\"passengers\": [{\"id\": \"01\", \"pclass\": 1, \"sex\": \"male\", \"age\": 29, \"sibsp\": 0, \"parch\": 0, \"fare\": 211.3, \"embarked\": \"C\"}]}"
}

### GET /sobreviventes
GET http://localhost:5555/sobreviventes
Content-Type: application/json

{
   "path":"/sobreviventes",
   "httpMethod":"GET"
}

### GET /sobreviventes/01
GET http://localhost:5555/sobreviventes?id=01
Content-Type: application/json

{
   "path":"/sobreviventes/10",
   "httpMethod":"GET",
   "pathParameters":{
      "id":"01"
   }
}

### DELETE /sobreviventes/01
DELETE http://localhost:5555/sobreviventes?id=70
Content-Type: application/json

{
   "path":"/sobreviventes/10",
   "httpMethod":"DELETE",
   "pathParameters":{
      "id":"01"
   }
}